server:
  port: 8888
  servlet:
    context-path: /api

spring:
  application:
    name: chen-blog

  profiles:
    active: dev

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.coon.blog.domain,com.coon.blog.dto
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-value: false
      logic-not-delete-value: true

